// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72z5-b_segrb-8e12hm_gPcfMzFSZVyc',
    appId: '1:817966952542:web:8a240fa497c8034478c4cf',
    messagingSenderId: '817966952542',
    projectId: 'pois-e3f88',
    authDomain: 'pois-e3f88.firebaseapp.com',
    storageBucket: 'pois-e3f88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJGuAGlstyWwSwiyKq2tguwbk_DBW-zU0',
    appId: '1:817966952542:android:fd356abd6997832778c4cf',
    messagingSenderId: '817966952542',
    projectId: 'pois-e3f88',
    storageBucket: 'pois-e3f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqpRTngtUnUllE-jCRieDVU_Krs2Tais',
    appId: '1:817966952542:ios:e2c42b9dae4a61ce78c4cf',
    messagingSenderId: '817966952542',
    projectId: 'pois-e3f88',
    storageBucket: 'pois-e3f88.appspot.com',
    iosClientId: '817966952542-hdji6kd5ape26m39d2oq6658805h1fsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pois',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqpRTngtUnUllE-jCRieDVU_Krs2Tais',
    appId: '1:817966952542:ios:e2c42b9dae4a61ce78c4cf',
    messagingSenderId: '817966952542',
    projectId: 'pois-e3f88',
    storageBucket: 'pois-e3f88.appspot.com',
    iosClientId: '817966952542-hdji6kd5ape26m39d2oq6658805h1fsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pois',
  );
}
